FROM public.ecr.aws/outerbounds/metaflow-base:latest  

# Set the CONDA_CHANNELS environment variable
ENV CONDA_CHANNELS=conda-forge,defaults

# (Optional) Install any other system-level dependencies you need
# RUN apt-get update && apt-get install -y --no-install-recommends some-system-package

# (Optional) Copy your requirements.txt (if you have one)
# COPY requirements.txt .

# (Optional) Install Python dependencies using pip
# RUN pip install -r requirements.txt